### ISSUE TITLE
Database dependent issue in getBalances (run tests on postgres)

### ISSUE THREAD

**Issue by afk11** [jpos/jPOS-EE#173]
https://github.com/jpos/jPOS-EE/blob/master/modules/minigl/src/test/java/org/jpos/gl/RulesTest.java#L132

This test doesn't pass if you use postgres. Instead of throwing an exception, it continues until the `fail()` call. The test passes successfully when using the test database - H2. Since it's using H2, GLSession will use getBalancesORM to look up the balance. When using postgres, it'll create a postgres dialect specific query instead.

Since there was a difference between H2/postgres I tweaked getBalances to always use getBalancesORM, to see if the tests agreed again, and they did.

It appears when using postgres, the wrong balance can be returned in that test (unsure why), but on H2 at least, the assertions based on the 48001 amount appear to hold. I'm not sure which is wrong (getBalancesORM / getBalances + postgres) because the transaction amount 48001 was probably chosen just because it triggers the error in tests.. which always used H2. 

To test with postgres, I created a hibernate.cfg.xml file in modules/minigl/src/main/test/resources, and in the TestBase and Import classes, made sure to have `db = new DB("hibernate.cfg.xml")` instead of `new DB()`. Also - you need to add `testImplementation project(':modules:db-postgresql')` to the minigl `build.gradle`

**Comment by ar** [comment]
This is a very good catch and a reminder of a very important issue related to native queries, which are fast, but have some constraints related to composite accounts.

The initial ORM-based query knows that a given account is a child of a given parent correctly using the `acct.parent` reference. The native queries cut some corners in order to take advantage of the database index, it assumes that the parent shares the `acct.code` prefix.

What happens here is that the test data has a parent account `11` with children `111,112,113` and `120`:

https://github.com/jpos/jPOS-EE/blob/dc905a2a/modules/minigl/src/test/resources/testdata.xml#L52-L66

ORM code considers account `120` as a child of `11` when computing the rule, but native code doesn't.

For the time being, I'll changed `testdata.xml` so that account `120` becomes `114`, but the native queries need further work to address this issue or at the very least, `GLSession.addAccount` could raise an exception if the child's code doesn't start with the same as parent.

Regarding your way of testing this, which is good, there's a simpler one; there's no need to create an `hibernate.cfg.xml`, you can use just the `db-postgresql` module and eventually tweak the `db.properties` file to point to your database. Also, there's now a handy `gls.forceDialect(GLSession.NativeDialect.ORM);` that you can use in Postgresql (or MySQL) to force the use of the ORM getBalances.

I'm keen to close this issue and open a related one as reminder that native composite balance has this issue, that we need to either fix (without bringing down performance) or at least clearly address in the documentation with a super big warning. Will wait for comments, though.

**Comment by afk11** [comment]
Thanks for looking into this! I see, that would explain it. I was aware of that quirk but didn't think of it this time. Quickly tried out replacing 120 with 114 and that passes for me.

Definitely agree on the big warning about the nested account code behaviour in getBalances, and a check in `GLSession.addAccount`. Should `Import.createFinal` should perform this check as well, if we provide a way disable the check for legacy systems that have non-canonical account codes but don't use mysql or postgres?

**Comment by ar** [comment]
Fully agree on `addAcount` and `Import.createFinal` checks.
