### ISSUE TITLE
Elasticsearch module - is not working async

### ISSUE THREAD

**Issue by nvolpe22** [jpos/jPOS-EE#204]
Hi, i'm trying to use the elasticsearch module as it appears in the documentation and it does not working like we expect.

In this commit https://github.com/jpos/jPOS-EE/commit/63b619a09f27ba7895ce551903681569dcad1965 we can see two main configuration files:
- modules/elasticsearch/src/main/resources/META-INF/q2/installs/deploy/00_logger_elastic.xml
- modules/elasticsearch/src/main/resources/META-INF/q2/installs/deploy/01_logger_elastic_daemon.xml

I configured both, and I don't see logs in kibana. So I then proceeded to set up a Remote JVM Debug application to debug both clases (ElasticSearchLogListener.java and ElasticSearchService.java)

When I run q2-outgoing (we set the module there), the ElasticSearchLogListener breakpoints stop the threads fine, and debugging I saw all works like we need.
But later when the message goes to the queue, the breakpoints into ElasticSearchService class never stop the threads and we don't see anything in elastic/kibana.. it's like this code has never been excecuted. 

Then I proceed to change the 01_logger_elastic_daemon.xml configuration as the attachment file (pulling out the logger tag).
[01_logger_elastic_daemon.xml.txt](https://github.com/jpos/jPOS-EE/files/5890040/01_logger_elastic_daemon.xml.txt)

Restart q2-outgoing and then the breakpoints into ElasticSearchService class stop the threads fine, and we can see all logs into Kibana correctly. 

Unfortunately, the code works synchronously and if elastic service is down, the transaction never go back to q2-incoming.

I'm missing something, right? 

Thanks!

**Comment by ar** [comment]
This contribution by Galih based on my elasticsearch PoC is actually confusing due to this file: https://github.com/jpos/jPOS-EE/blob/master/modules/elasticsearch/src/main/resources/META-INF/q2/installs/deploy/01_logger_elastic_daemon.xml

It's wrapped by a `<logger>` element that makes no sense as this is not a LogListener but a QBean itself.

The basic idea is that the LogListener is decoupled from the daemon through the jPOS space.

This was fixed in bd475f11.
